version: "2"
linters:
  enable:
    - forbidigo
    - godot
    - misspell
    - revive
    - unconvert
  settings:
    cyclop:
      max-complexity: 15
      package-average: 0
    forbidigo:
      forbid:
        - pattern: fmt\.Print.*
    godot:
      scope: declarations
      exclude:
        - '^fixme:'
        - '^todo:'
      capital: false
      period: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - path: util
        text: 'var-naming: avoid meaningless package names'
        linters:
          - revive
issues:
  fix: true
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/vorlif/spreak
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
